#/wp-dev-boilerplate/docker-compose.yml
---
version: '3.3'
services:
  db:
    container_name: 'db'
    image: mariadb:latest
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - $MYSQL_LOCAL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD      

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    #image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $WP_LOCAL_PORT:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      XDEBUG_CONFIG: $XDEBUG_CONFIG
    volumes:
      - ./wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins

volumes:
  dbdata: {}
  wordpress: {}
  plugins: {}